name: iris-gan
channels:
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - pillow
  - tqdm
  - pip
  - pip:
      - opencv-python
